# Generated by Django 5.2.11 on 2026-03-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NFLGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "espn_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("home_team", models.CharField(max_length=60)),
                ("away_team", models.CharField(max_length=60)),
                ("home_abbr", models.CharField(max_length=6)),
                ("away_abbr", models.CharField(max_length=6)),
                ("game_date", models.DateTimeField()),
                ("week", models.IntegerField(blank=True, null=True)),
                ("season", models.IntegerField()),
                ("season_type", models.IntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("final", "Final"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("period", models.IntegerField(default=0)),
                ("display_clock", models.CharField(blank=True, max_length=10)),
                ("home_q1", models.IntegerField(blank=True, null=True)),
                ("home_q2", models.IntegerField(blank=True, null=True)),
                ("home_q3", models.IntegerField(blank=True, null=True)),
                ("home_q4", models.IntegerField(blank=True, null=True)),
                ("home_ot", models.IntegerField(blank=True, null=True)),
                ("home_total", models.IntegerField(blank=True, null=True)),
                ("away_q1", models.IntegerField(blank=True, null=True)),
                ("away_q2", models.IntegerField(blank=True, null=True)),
                ("away_q3", models.IntegerField(blank=True, null=True)),
                ("away_q4", models.IntegerField(blank=True, null=True)),
                ("away_ot", models.IntegerField(blank=True, null=True)),
                ("away_total", models.IntegerField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NFL Game",
                "verbose_name_plural": "NFL Games",
                "ordering": ["game_date"],
            },
        ),
    ]
