# Generated by Django 5.2.11 on 2026-03-01 01:31

import boards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "entry_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Instructions shown to participants (payment info, Venmo, etc.)",
                    ),
                ),
                ("payout_q1_pct", models.PositiveSmallIntegerField(default=25)),
                ("payout_q2_pct", models.PositiveSmallIntegerField(default=25)),
                ("payout_q3_pct", models.PositiveSmallIntegerField(default=25)),
                ("payout_q4_pct", models.PositiveSmallIntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_token",
                    models.CharField(
                        db_index=True,
                        default=boards.models._gen_token,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Numbers have been assigned; no new claims allowed.",
                    ),
                ),
                ("numbers_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("home_numbers", models.JSONField(blank=True, null=True)),
                ("away_numbers", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="games.nflgame",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Square",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField()),
                ("col", models.PositiveSmallIntegerField()),
                ("name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squares",
                        to="boards.board",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["row", "col"],
                "unique_together": {("board", "row", "col")},
            },
        ),
    ]
