# Generated by Django 5.2.11 on 2026-05-09 00:26

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='access_token',
            field=models.CharField(db_index=True, default=boards.models._gen_token, max_length=32, unique=True),
        ),
    ]
